### ISSUE TITLE
libcxx should avoid using xlocinfo.h private header -- file does not exist in VS2022

### ISSUE THREAD

**Issue by mosherbrian** [enlyze/libcxx#1]
libc++ should avoid using xlocinfo.h. It is a Microsoft-private implementation header that does not exist in Visual Studio 2022. It is used in [libcxx/include/support/win32/locale_win32.h](https://github.com/enlyze/libcxx/blob/da422159b0fbb47815b4922ca15e77afe10d8fea/include/support/win32/locale_win32.h#L15).

This issue was resolved in in the upstream libc++ [here](https://reviews.llvm.org/D99213) in March 2021.

**Comment by ColinFinck** [comment]
Fixed now thanks to @solemnwarning's work on libc++ 17.0.6 for VS2022 in #2
